### PR TITLE
logging revamp

### PR DESCRIPTION
**Pull request by williamstark01**
* use a logger for logging (recommended way of using logging)
* use "handlers" with logger to print output in both the terminal and the log file
* rename log file to `ensembl_anno.log`
* use ISO datetime format in log messages (excluding "T" which decreases readability)
* remove name of the logger used to log the call in log messages, as it's always the same

### CODE REVIEW

**Review by thibauthourlier — CHANGES_REQUESTED** [review]
I know that the script has not been used by many people yet, however I think that changing the name of the log file for no apparent reasons shouldn't happen. So I would recommend to keep AnnoLogFile.log
Same remark for the formatting
Of course the two remarks above can be discussed and are mostly there because of the PR message
I think it should use a config file instead of code to configure the logger, YAML or ini doesn't matter much
As we are not in real production mode, DEBUG is fine however I think that it should be INFO latter
I know a config is easily modifyable but we may want to have a verbose option to change the log level on the command line
More a question, there is already `from pathlib import Path`, should `import pathlib` be there or whatever added to the `from...` to avoid two pathlib line?

**Comment by williamstark01** [comment]
> I know that the script has not been used by many people yet, however I think that changing the name of the log file for no apparent reasons shouldn't happen. So I would recommend to keep AnnoLogFile.log

I thought that the log file name could be improved. Changing it won't create any issues with previous annotations having a different name for this file. Mirroring the script name is an option I think makes sense, but I'm open to other suggestions. For example, I thought of including annotation-specific identifiers to the file name, but since it is stored in an annotation-specific working directory this didn't seem necessary.

> Same remark for the formatting

ISO format timestamps are recommended and standard in log files. And granted that with logging signal vs noise is an important consideration in general, I simplified the format, but let me know if anything more needs to be included.

> Of course the two remarks above can be discussed and are mostly there because of the PR message I think it should use a config file instead of code to configure the logger, YAML or ini doesn't matter much

A config file would certainly be useful if we adopt a more extensive configuration, but I think adding an extra file for the current short configuration isn't warranted. I don't feel strongly about this though.

> As we are not in real production mode, DEBUG is fine however I think that it should be INFO latter I know a config is easily modifyable but we may want to have a verbose option to change the log level on the command line

That's a good idea, adding an option to adjust logging level would help a lot with signal vs noise.

> More a question, there is already `from pathlib import Path`, should `import pathlib` be there or whatever added to the `from...` to avoid two pathlib line?

Just to write down my thoughts on this from our discussion a couple of days ago:

I believe using `pathlib.Path` instead of `Path` increases code readability, and most importantly helps other maintainers who are not as familiar with a specific library (pathlib in this case) to discover it, and potentially also use it. Just `Path` in the code removes context, it could be a class defined by a previous maintainer, and the person who sees it would need to proactively search for it to discover its origin. I didn't want to change every occurrence of `Path` in the code though before we discussed and agreed about this, so I'm open to hearing everyone's thoughts.

**Comment by thibauthourlier** [comment]
Part of my problems with some of your changes is the description of the PR and what's in the PR.
The description says "use logger instead of logging" and "print to both terminal and log file". Because of the number of occurrence of logging, this is painful to look at but nothing can be done about it. That also means that some changes might not be properly check because of the amount of lines to scroll down.

Then there are two changes which are unrelated to the description.

The file name, I wouldn't have chosen it and I think your proposed name is better, but I don't think the change should be there because it is not in the description and it is changing a file name. If the change had been in it's own PR I would have probably simply approved it.

As I said, the format is a similar problem, I have no problem using any standard but the current format may have been set for a specific reason.

Now I could almost say that the changes to logging and the changes for the terminal/log file should be in a different PR but they have been described in the description

Because there are two handlers I think a configuration file is needed

I don't really see a problem to use `pathlib.Path` in the code, however I'm not sure people will "discover" it more in this form instead of `Path` as it's imported with `from pathlib import Path`

**Comment by thibauthourlier** [comment]
I also forgot to say that f-string should not be use in the logging message

**Comment by williamstark01** [comment]
@thibauthourlier you are right, some of the edits are indeed not easy to find in the current long diff. I'm updating the PR name and description to reflect the edits better.

> I also forgot to say that f-string should not be use in the logging message

You are right, I've read about this one but forgot, fixing it now.

**Review by thibauthourlier — APPROVED** [review]
Looks fine to me

**Pull request merged**
